apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ad-management

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - ingress.yaml
